//java.util.AbstractMap
//java.lang.Object
//java.util.List

import java.util.Date;

public class Owes_To_Or_From {

    private int id;
    private char tag;
    private char [] To_Or_From; //loan given or taken
    private int amount;
    private char [] mode_of_payment;
    private boolean sign;
    private char [] status ; // whether paid or not - paid/not_paid?
    Date OnDate = Date();
}
//the above mentioned tasks are yet to be implemented

// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO
// CALL ME WHEN THERE IS MORE WORK TO DO